# 5일차

# 1.셀레니움


> 크롬 드라이브 확인 후 크롬 드라이버 다운로드 > 경로상에 넣어주기
> !pip install Seleninum
> !pip install requests
> !pip install BeautifulSoup
> !pip install webdriver-manager


In [14]:
!pip install Selenium
!apt-get update
!apt install chromium-chromedriver
import requests
from bs4 import BeautifulSoup as bs
from selenium.webdriver.common.keys import Keys
from selenium import webdriver

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless') #내부 창을 띄울 수 없으므로 설정
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')

wd = webdriver.Chrome('chromedriver',chrome_options=chrome_options) # wd라는 객체에 크롬 드라이버 넣어줌
# 드라이버가 찾아서 들어온것으로 생각 설치해줘야하는 경우가 있으면 드라이버 설치해주면됨
wd.get("https://vibe.naver.com/chart/total")
#.get url에 접근하는 메소드

# 네이버 뮤직에서 크롤링
html = wd.page_source
soup = bs(html, 'html.parser')

# 순위, 가수명, 노래제목 리스트형태로 출력
song_box = soup.find('tbody')
songs = song_box.select('td.song')

song_rank = []
rank = 1
for i in songs:
    ranks = str(rank) + "위"
    title = i.select_one('a.link_text').get('title')
    # select_one은 가장 처음의 <a>태그를 찾고 바로 속성값을 얻을 수 있음
    # a태그 내 class link_text를 찾고 .get('title')로 title태그의 내용을 불러옴
    singers = i.select_one('a.link_artist').text
    # a태그 내 link_artist 클래스를 찾고 텍스트만 불러온다
    song_rank.append([ranks, title, singers])
    # song_rank라는 빈리스트에 append 메소드를 이용해 ranks, title, singers를 추가함
    rank += 1
print(song_rank)

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Hit:1 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease
Get:2 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Ign:3 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Hit:4 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Hit:5 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
Hit:6 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:7 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic InRelease
Get:9 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Hit:10 http://ppa.launchpad.net/cran/libgit2/ubuntu bionic InRelease
Get:11 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [83.3 kB]
Hit:12 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic InRelease
Hit:13 http://ppa.launchpad.

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:14: DeprecationWarning: use options instead of chrome_options
  


[['1위', '사건의 지평선', '윤하'], ['2위', 'After LIKE', 'IVE(아이브)'], ['3위', 'Nxde', '(여자) 아이들'], ['4위', 'ANTIFRAGILE', 'LE SSERAFIM (르세라핌)'], ['5위', 'Hype boy', 'NewJeans'], ['6위', '새삥 (Prod. ZICO) (Feat. 호미들)', '지코 (ZICO)'], ['7위', 'LOVE DIVE', 'IVE(아이브)'], ['8위', 'Attention', 'NewJeans'], ['9위', 'Shut Down', 'BLACKPINK'], ['10위', 'Monologue', '테이'], ['11위', 'Pink Venom', 'BLACKPINK'], ['12위', 'Rush Hour (Feat. j-hope of BTS)', 'Crush'], ['13위', '자격지심 (Feat. ZICO)', "BE'O(비오)"], ['14위', '그때 그 순간 그대로 (그그그)', 'WSG워너비(가야G)'], ['15위', '너의 모든 순간', '성시경'], ['16위', '나의 X에게', '경서'], ['17위', 'TOMBOY', '(여자) 아이들'], ['18위', '드라마', '아이유(IU)'], ['19위', 'ELEVEN', 'IVE(아이브)'], ['20위', '그라데이션', '10CM'], ['21위', 'FEARLESS', 'LE SSERAFIM (르세라핌)'], ['22위', '우린 그렇게 사랑해서', '강민경'], ['23위', "That's Hilarious", 'Charlie Puth'], ['24위', 'Cookie', 'NewJeans'], ['25위', '취중고백', '김민석(멜로망스)'], ['26위', '어떻게 이별까지 사랑하겠어, 널 사랑하는 거지', 'AKMU(악뮤)'], ['27위', '주저하는 연인들을 위해', '잔나비'], ['28위', 'LAW (Prod. Czaer)', '윤미래'], ['29위', '도깨비

# 3. 배열구조

## 3-1) 리스트 배열구조



In [15]:
li1 = [1, 2, 3, 4, 'a', 'b']
li2 = [5, 6, 'c', 'd']
print(li1, type(li1))
print(li2, type(li2))
print(li1[2])

print(li1 + li2)
print(li2 * 3)



[1, 2, 3, 4, 'a', 'b'] <class 'list'>
[5, 6, 'c', 'd'] <class 'list'>
3
[1, 2, 3, 4, 'a', 'b', 5, 6, 'c', 'd']
[5, 6, 'c', 'd', 5, 6, 'c', 'd', 5, 6, 'c', 'd']


## 3-2) 넘파이 배열구조

In [23]:
import numpy as np

# 넘파이 배열을 만들 때 np.array([])
ar1 = np.array([1,2,3,4,'a','b'])
ar2 = np.array([[1, 2], [3, 4]])
ar3 = np.array([[5, 6], [7, 8]])
print(ar1, type(ar1))
print(type(ar1.dtype))

# 정수와 실수 > 실수
# 정수와 문자열 > 문자열
# 실수와 문자열 > 문자열

print(ar2 + ar3)

['1' '2' '3' '4' 'a' 'b'] <class 'numpy.ndarray'>
<class 'numpy.dtype[str_]'>
[[ 6  8]
 [10 12]]


# 4. 넘파이

## 4-3) 넘파이 속성

In [37]:
import numpy as np

# 1차원 배열
arr1 = np.array([1.0, 20])
print(arr1, type(arr1))
print(arr1[1])

# 2차원 배열(행과 열이 생김)
arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)
print(arr2[0][1])

# 크기 .shape
print(arr1.shape)
print(arr2.shape)

# 차원 .ndim
print(arr1.ndim)
print(arr2.ndim)

# 총 원소 개수 size
print(arr1.size)
print(arr2.size)

# 원소들의 데이터 타입
print(arr1.dtype)
print(arr2.dtype)

[ 1. 20.] <class 'numpy.ndarray'>
20.0
[[1 2 3]
 [4 5 6]]
2
(2,)
(2, 3)
1
2
2
6
float64
int64


## 4-4) 넘파이 함수

In [54]:
# 넘파이 검색, 수정, 추가, 삭제
arr1 = np.array([1.0, 20])
arr2 = np.array([[1,2,3], [4,5,6]])

# 검색(추출, 색인)
print(arr1[1])
print(arr2[1][1])
print(arr2[0][2])
print(arr2[0])

# 수정(기존에 있는 값이 변경된 값으로 변수에 재할당)
print(arr1[0])
# arr1[0] > 10으로 값 변경
arr1[0] = 10
print(arr1[0])

# arr2에서 0행 1열을 7로 변경
arr2[0][1] = 7
print(arr2)

# 추가(변수에 재할당)
arr3 = np.array([[0, 0], [0, 0]])
print(arr3)
print(arr3.ndim)

# 행 추가
arr3 = np.append(arr3, [[1, 1]], axis = 0) # 배열 그대로 행 추가
print(arr3)

# 열 추가
arr4 = np.append(arr3, [[1,1], [2,2], [3,3]], axis = 1) # axis = 1 뒷쪽에 추가됨을 확인
print(arr4)

# 삭제
# np.delete(배열, 인덱스, 축)
# axis = 0 > 행,  axis 1 > 열(2차원)
# axis = 0 > 높이, axis 1 > 행, axis = 2 > 열(3차원)

print(np.delete(arr4, 1, axis = 0)) # 2행 삭제
print(np.delete(arr4, 1, axis = 1)) # 2열 삭제



20.0
5
3
[1 2 3]
1.0
10.0
[[1 7 3]
 [4 5 6]]
[[0 0]
 [0 0]]
2
[[0 0]
 [0 0]
 [1 1]]
[[0 0 1 1]
 [0 0 2 2]
 [1 1 3 3]]
[[0 0 1 1]
 [1 1 3 3]]
[[0 1 1]
 [0 2 2]
 [1 3 3]]
